### ISSUE TITLE
Error when pressing escape to close the right-hand-side slide-out menu

### ISSUE THREAD

**Issue by danielweck** [readium/readium-desktop#335]
```
AccessibleMenu.tsx:99 Uncaught TypeError: this.props.focusMenuButton is not a function
    at AccessibleMenu.handleKey (AccessibleMenu.tsx:99)
handleKey @ AccessibleMenu.tsx:99`
```
![ThoriumFocusEscapeKeyError](https://user-images.githubusercontent.com/625201/60912428-34aee680-a27d-11e9-9475-f3c78fa8d15a.png)

**Comment by danielweck** [comment]
Related issue: https://github.com/readium/readium-desktop/issues/336

**Comment by panaC** [comment]
fixed

**Comment by danielweck** [comment]
Hello @panaC the bug still exists in the develop branch, could you please specify the PR that addresses this issue? Thanks! :)

**Comment by panaC** [comment]
![Screenshot 2019-07-03 at 17 51 36](https://user-images.githubusercontent.com/3198865/60606240-4b57c800-9dbb-11e9-8fd6-28b01fb8af85.png)

my fault, sorry, but what is the purpose of this function ? @Scarsniik
